export const MOTIVATIONAL_PHRASES = [
    // 1-50: Gentle encouragement
    "Keep going!",
    "You're doing great!",
    "Stay consistent!",
    "Every step counts!",
    "Small progress is still progress!",
    "Persistence pays off!",
    "Believe in yourself!",
    "You got this!",
    "One day at a time!",
    "Keep up the good work!",
    "Stay focused!",
    "You're building a great habit!",
    "Keep the streak alive!",
    "Every day matters!",
    "You're on the right track!",
    "Keep pushing forward!",
    "Consistency is key!",
    "You're making it happen!",
    "Stay motivated!",
    "Keep your eyes on the prize!",
    "You're stronger than you think!",
    "Keep showing up!",
    "Every day is a win!",
    "You're making progress!",
    "Keep believing!",
    "You're unstoppable!",
    "Stay positive!",
    "You're doing something amazing!",
    "Keep your momentum!",
    "You're inspiring!",
    "Stay determined!",
    "You're making a difference!",
    "Keep your head up!",
    "You're getting better every day!",
    "Stay on course!",
    "You're building something great!",
    "Keep your streak going!",
    "You're doing something special!",
    "Stay strong!",
    "You're making it look easy!",
    "Keep your energy up!",
    "You're on a roll!",
    "Stay committed!",
    "You're crushing it!",
    "Keep your spirits high!",
    "You're making yourself proud!",
    "Stay dedicated!",
    "You're doing fantastic!",
    "Keep shining!",
    // 51-150: More enthusiastic encouragement
    "Amazing job!",
    "You're really getting the hang of this!",
    "Your dedication is impressive!",
    "You're building a powerful habit!",
    "Keep up the amazing work!",
    "You're a streak superstar!",
    "Your consistency is inspiring!",
    "You're making dreams happen!",
    "Keep smashing your goals!",
    "You're a champion!",
    "Your effort is paying off!",
    "You're a role model!",
    "Keep up the momentum!",
    "You're a streak legend!",
    "Your progress is incredible!",
    "You're making history!",
    "Keep breaking barriers!",
    "You're a force to be reckoned with!",
    "Your streak is on fire!",
    "You're a true go-getter!",
    "Keep up the fantastic work!",
    "You're a streak machine!",
    "Your commitment is next level!",
    "You're a daily hero!",
    "Keep up the streak magic!",
    "You're a consistency king/queen!",
    "Your streak is unstoppable!",
    "You're a daily inspiration!",
    "Keep up the greatness!",
    "You're a streak master!",
    "Your dedication is unmatched!",
    "You're a daily legend!",
    "Keep up the winning streak!",
    "You're a streak warrior!",
    "Your progress is phenomenal!",
    "You're a daily champion!",
    "Keep up the streak power!",
    "You're a streak superstar!",
    "Your streak is legendary!",
    "You're a daily powerhouse!",
    "Keep up the streak energy!",
    "You're a streak icon!",
    "Your streak is awe-inspiring!",
    "You're a daily streaker!",
    "Keep up the streak fire!",
    "You're a streak sensation!",
    "Your streak is mind-blowing!",
    "You're a daily streak master!",
    "Keep up the streak excellence!",
    "You're a streak phenomenon!",
    "Your streak is world-class!",
    "You're a daily streak legend!",
    "Keep up the streak brilliance!",
    "You're a streak champion!",
    "Your streak is record-breaking!",
    "You're a daily streak hero!",
    "Keep up the streak domination!",
    "You're a streak superstar!",
    "Your streak is extraordinary!",
    "You're a daily streak king/queen!",
    "Keep up the streak greatness!",
    "You're a streak master!",
    "Your streak is phenomenal!",
    "You're a daily streak warrior!",
    "Keep up the streak power!",
    "You're a streak legend!",
    "Your streak is unstoppable!",
    "You're a daily streak champion!",
    "Keep up the streak energy!",
    "You're a streak icon!",
    "Your streak is awe-inspiring!",
    "You're a daily streaker!",
    "Keep up the streak fire!",
    "You're a streak sensation!",
    "Your streak is mind-blowing!",
    "You're a daily streak master!",
    "Keep up the streak excellence!",
    "You're a streak phenomenon!",
    "Your streak is world-class!",
    "You're a daily streak legend!",
    "Keep up the streak brilliance!",
    "You're a streak champion!",
    "Your streak is record-breaking!",
    "You're a daily streak hero!",
    "Keep up the streak domination!",
    // 151-250: High praise and celebration
    "Incredible achievement!",
    "You're a streak superstar!",
    "Your dedication is out of this world!",
    "You're a streak legend!",
    "Your streak is the stuff of legends!",
    "You're a streak master!",
    "Your streak is a masterpiece!",
    "You're a streak icon!",
    "Your streak is a work of art!",
    "You're a streak phenomenon!",
    "Your streak is a marvel!",
    "You're a streak sensation!",
    "Your streak is a wonder!",
    "You're a streak hero!",
    "Your streak is a triumph!",
    "You're a streak champion!",
    "Your streak is a victory!",
    "You're a streak king/queen!",
    "Your streak is a conquest!",
    "You're a streak conqueror!",
    "Your streak is a feat!",
    "You're a streak winner!",
    "Your streak is a success!",
    "You're a streak achiever!",
    "Your streak is a glory!",
    "You're a streak star!",
    "Your streak is a treasure!",
    "You're a streak gem!",
    "Your streak is a jewel!",
    "You're a streak diamond!",
    "Your streak is a gold medal!",
    "Your streak is a trophy!",
    "Your streak is a prize!",
    "Your streak is a reward!",
    "Your streak is a celebration!",
    "Your streak is a party!",
    "Your streak is a festival!",
    "Your streak is a parade!",
    "Your streak is a fireworks show!",
    "Your streak is an extravaganza!",
    "Your streak is a spectacle!",
    "Your streak is a showstopper!",
    "Your streak is a standing ovation!",
    "Your streak is an encore!",
    "Your streak is a curtain call!",
    "Your streak is a finale!",
    "Your streak is a grand finale!",
    "Your streak is a legend!",
    "Your streak is a myth!",
    "Your streak is a saga!",
    "Your streak is an epic!",
    "Your streak is a journey!",
    "Your streak is an adventure!",
    "Your streak is a quest!",
    "Your streak is an odyssey!",
    "Your streak is a voyage!",
    "Your streak is an expedition!",
    "Your streak is a mission!",
    "Your streak is a crusade!",
    "Your streak is a campaign!",
    "Your streak is an operation!",
    "Your streak is a project!",
    "Your streak is an enterprise!",
    "Your streak is a venture!",
    "Your streak is a pursuit!",
    "Your streak is a chase!",
    "Your streak is a hunt!",
    "Your streak is a race!",
    "Your streak is a marathon!",
    "Your streak is a sprint!",
    "Your streak is a relay!",
    "Your streak is a dash!",
    "Your streak is a run!",
    "Your streak is a jog!",
    "Your streak is a walk!",
    "Your streak is a hike!",
    "Your streak is a climb!",
    "Your streak is a trek!",
    "Your streak is a journey!",
    "Your streak is a voyage!",
    "Your streak is an adventure!",
    "Your streak is a quest!",
    "Your streak is a legend!",
    // 251-365: Major celebration, huge congratulations
    "Unbelievable! You're a streak legend!",
    "Absolutely phenomenal! Your streak is historic!",
    "Legendary! You've set a new standard!",
    "Epic achievement! You're unstoppable!",
    "World-class dedication! You're a streak icon!",
    "Record-breaking! You're rewriting the rules!",
    "Astonishing! Your streak is the stuff of dreams!",
    "You are a streak superstar! The world is watching!",
    "Unmatched commitment! You're a streak hero!",
    "You are a streak inspiration to all!",
    "Your streak is a beacon of excellence!",
    "You are a streak champion of champions!",
    "Your streak is a triumph of willpower!",
    "You are a streak master! The best of the best!",
    "Your streak is a legendary saga!",
    "You are a streak conqueror! Nothing can stop you!",
    "Your streak is a marvel of consistency!",
    "You are a streak phenomenon!",
    "Your streak is a masterpiece of dedication!",
    "You are a streak icon! The ultimate example!",
    "Your streak is a world record!",
    "You are a streak king/queen! All hail your streak!",
    "Your streak is a global inspiration!",
    "You are a streak champion! The world applauds you!",
    "Your streak is a monumental achievement!",
    "You are a streak legend! History remembers you!",
    "Your streak is a testament to greatness!",
    "You are a streak superstar! The world celebrates you!",
    "Your streak is a triumph for the ages!",
    "You are a streak hero! The world cheers for you!",
    "Your streak is a victory for all time!",
    "You are a streak master! The world bows to you!",
    "Your streak is a saga of success!",
    "You are a streak conqueror! The world admires you!",
    "Your streak is a legend for the ages!",
    "You are a streak icon! The world is inspired!",
    "Your streak is a masterpiece for the world!",
    "You are a streak phenomenon! The world is amazed!",
    "Your streak is a marvel for all to see!",
    "You are a streak superstar! The world is in awe!",
    "Your streak is a triumph for the world!",
    "You are a streak champion! The world celebrates!",
    "Your streak is a victory for the world!",
    "You are a streak legend! The world remembers!",
    "Your streak is a testament to greatness for all!",
    "You are a streak superstar! The world celebrates you!",
    "Your streak is a triumph for the ages!",
    "You are a streak hero! The world cheers for you!",
    "Your streak is a victory for all time!",
    "You are a streak master! The world bows to you!",
    "Your streak is a saga of success!",
    "You are a streak conqueror! The world admires you!",
    "Your streak is a legend for the ages!",
    "You are a streak icon! The world is inspired!",
    "Your streak is a masterpiece for the world!",
    "You are a streak phenomenon! The world is amazed!",
    "Your streak is a marvel for all to see!",
    "You are a streak superstar! The world is in awe!",
    "Your streak is a triumph for the world!",
    "You are a streak champion! The world celebrates!",
    "Your streak is a victory for the world!",
    "You are a streak legend! The world remembers!",
    "Your streak is a testament to greatness for all!",
    "You are a streak superstar! The world celebrates you!",
    "Your streak is a triumph for the ages!",
    "You are a streak hero! The world cheers for you!",
    "Your streak is a victory for all time!",
    "You are a streak master! The world bows to you!",
    "Your streak is a saga of success!",
    "You are a streak conqueror! The world admires you!",
    "Your streak is a legend for the ages!",
    "You are a streak icon! The world is inspired!",
    "Your streak is a masterpiece for the world!",
    "You are a streak phenomenon! The world is amazed!",
    "Your streak is a marvel for all to see!",
    "You are a streak superstar! The world is in awe!",
    "Your streak is a triumph for the world!",
    "You are a streak champion! The world celebrates!",
    "Your streak is a victory for the world!",
    "You are a streak legend! The world remembers!",
    "Your streak is a testament to greatness for all!",
    "You are a streak superstar! The world celebrates you!",
    "Your streak is a triumph for the ages!",
    "You are a streak hero! The world cheers for you!",
    "Your streak is a victory for all time!",
    "You are a streak master! The world bows to you!",
    "Your streak is a saga of success!",
    "You are a streak conqueror! The world admires you!",
    "Your streak is a legend for the ages!",
    "You are a streak icon! The world is inspired!",
    "Your streak is a masterpiece for the world!",
    "You are a streak phenomenon! The world is amazed!",
    "Your streak is a marvel for all to see!",
    "You are a streak superstar! The world is in awe!",
    "Your streak is a triumph for the world!",
    "You are a streak champion! The world celebrates!",
    "Your streak is a victory for the world!",
    "You are a streak legend! The world remembers!",
    "Your streak is a testament to greatness for all!",
];
